
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN DIVIDE ELSE FALSE ID IF LBRACE LPAREN MINUS NUMBER PLUS PRINT RBRACE RPAREN SEMICOLON STRING TIMES TRUE WHILEprogram : statement_liststatement_list : statement_list statement\n| statementstatement : ID ASSIGN expression SEMICOLONstatement : PRINT LPAREN expression RPAREN SEMICOLONexpression : expression PLUS expression\n| expression MINUS expressionexpression : NUMBERexpression : ID'
    
_lr_action_items = {'ID':([0,2,3,6,7,8,13,14,15,19,],[4,4,-3,-2,9,9,-4,9,9,-5,]),'PRINT':([0,2,3,6,13,19,],[5,5,-3,-2,-4,-5,]),'$end':([1,2,3,6,13,19,],[0,-1,-3,-2,-4,-5,]),'ASSIGN':([4,],[7,]),'LPAREN':([5,],[8,]),'NUMBER':([7,8,14,15,],[11,11,11,11,]),'SEMICOLON':([9,10,11,16,17,18,],[-9,13,-8,19,-6,-7,]),'PLUS':([9,10,11,12,17,18,],[-9,14,-8,14,14,14,]),'MINUS':([9,10,11,12,17,18,],[-9,15,-8,15,15,15,]),'RPAREN':([9,11,12,17,18,],[-9,-8,16,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,],[2,]),'statement':([0,2,],[3,6,]),'expression':([7,8,14,15,],[10,12,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','tracelang_parser.py',8),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','tracelang_parser.py',13),
  ('statement_list -> statement','statement_list',1,'p_statement_list','tracelang_parser.py',14),
  ('statement -> ID ASSIGN expression SEMICOLON','statement',4,'p_statement_assign','tracelang_parser.py',22),
  ('statement -> PRINT LPAREN expression RPAREN SEMICOLON','statement',5,'p_statement_print','tracelang_parser.py',27),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','tracelang_parser.py',32),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','tracelang_parser.py',33),
  ('expression -> NUMBER','expression',1,'p_expression_number','tracelang_parser.py',38),
  ('expression -> ID','expression',1,'p_expression_id','tracelang_parser.py',43),
]
